version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

install:
    - choco install atom -y
    - choco upgrade atom
    - cd %APPVEYOR_BUILD_FOLDER%
    - "%LOCALAPPDATA%/atom/bin/apm clean"
    - "%LOCALAPPDATA%/atom/bin/apm install"

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - "%LOCALAPPDATA%/atom/bin/apm test --path %LOCALAPPDATA%/atom/bin/atom.cmd"
